import assert from 'node:assert/strict';
import { sanitizeHtml } from '../lib/admin/sanitize.js';
const t = (i, o, inl) => assert.equal(sanitizeHtml(i, inl), o, i);
t('<p>שלום <b>עולם</b></p>', '<p>שלום <b>עולם</b></p>');
t('<p onclick="x()">a</p><script>alert(1)</script>', '<p>a</p>');
t('<a href="javascript:alert(1)">x</a>', '<a>x</a>');
t('<a href="https://other.com/">x</a>', '<a href="https://other.com/" target="_blank" rel="noopener">x</a>');
t('<img src=x onerror=alert(1)>', '');
t('<p><img src="/wp-content/uploads/a.jpg" alt=\'"><script>\'></p>', '<p><img src="/wp-content/uploads/a.jpg" alt="&quot;&gt;&lt;script&gt;" loading="lazy" decoding="async"></p>');
t('<div>one</div><div class="vision x">two</div>', '<p>one</p><div class="vision">two</div>');
t('<h1>T</h1><span style="color:red">s</span>', '<h2>T</h2>s');
t('<p>https://youtu.be/dQw4w9WgXcQ</p>', sanitizeHtml('<p>https://www.youtube.com/watch?v=dQw4w9WgXcQ</p>'));
assert.match(sanitizeHtml('<p>https://youtu.be/dQw4w9WgXcQ</p>'), /data-yt="dQw4w9WgXcQ"/);
t('<p>a</p><p> </p><p><br></p>', '<p>a</p>');
t('<p>a <b>b</p>', '<p>a <b>b</b></p>');
t('<p>1 < 2 & 3 &amp; 4</p>', '<p>1 &lt; 2 &amp; 3 &amp; 4</p>');
t('<p>x</p><p>y</p>', 'x y', true);
t('<style>p{}</style><iframe src="x"></iframe>ok', 'ok');
t('<p>a<!-- c --></p>', '<p>a</p>');
t('<svg><script>1</script></svg><p>z</p>', '<p>z</p>');
t('<a href="/x/" title="t">in</a>', '<a href="/x/">in</a>');
console.log('sanitize: all passed');
